import type { Resource, ResourceCategory } from "./types"

export const MOCK_RESOURCE_CATEGORIES: ResourceCategory[] = [
  {
    _id: "cat-ui-libraries",
    _type: "resourceCategory",
    title: "UI & Components",
    slug: { current: "ui-components" },
    icon: "Box",
    color: "#3b82f6",
    order: 1,
  },
  {
    _id: "cat-icons-assets",
    _type: "resourceCategory",
    title: "Icons & Assets",
    slug: { current: "icons-assets" },
    icon: "Sparkles",
    color: "#f59e0b",
    order: 2,
  },
  {
    _id: "cat-shaders-canvas",
    _type: "resourceCategory",
    title: "CSS & Shaders",
    slug: { current: "css-shaders" },
    icon: "Flame",
    color: "#ec4899",
    order: 3,
  },
  {
    _id: "cat-motion-interactions",
    _type: "resourceCategory",
    title: "Motion & Physics",
    slug: { current: "motion-physics" },
    icon: "Play",
    color: "#a855f7",
    order: 4,
  },
  {
    _id: "cat-ai-devtools",
    _type: "resourceCategory",
    title: "Dev & AI Tools",
    slug: { current: "dev-ai-tools" },
    icon: "Cpu",
    color: "#10b981",
    order: 5,
  },
  {
    _id: "cat-typography-fonts",
    _type: "resourceCategory",
    title: "Typography",
    slug: { current: "typography" },
    icon: "Type",
    color: "#06b6d4",
    order: 6,
  },
  {
    _id: "cat-colors-gradients",
    _type: "resourceCategory",
    title: "Colors & Themes",
    slug: { current: "colors-themes" },
    icon: "Palette",
    color: "#f43f5e",
    order: 7,
  },
  {
    _id: "cat-inspiration-design",
    _type: "resourceCategory",
    title: "Inspiration & Labs",
    slug: { current: "inspiration-labs" },
    icon: "Compass",
    color: "#8b5cf6",
    order: 8,
  },
]

export const MOCK_RESOURCES: Resource[] = [
  {
    _id: "res-shadcn-ui",
    _type: "resource",
    title: "shadcn/ui",
    slug: { current: "shadcn-ui" },
    url: "https://ui.shadcn.com",
    description:
      "Beautifully designed components that you can copy and paste into your apps. Accessible, customizable, and fully open-source.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1200&auto=format&fit=crop",
      alt: "shadcn/ui component library preview",
    },
    logo: {
      url: "https://ui.shadcn.com/favicon.ico",
      alt: "shadcn/ui logo",
    },
    category: MOCK_RESOURCE_CATEGORIES[0],
    pricing: "MIT",
    isFeatured: true,
    publishedAt: "2026-08-15T08:00:00.000Z",
  },
  {
    _id: "res-aceternity-ui",
    _type: "resource",
    title: "Aceternity UI",
    slug: { current: "aceternity-ui" },
    url: "https://ui.aceternity.com",
    description:
      "Trending UI components crafted with Framer Motion and Tailwind CSS. Perfect for modern SaaS landing pages and hero sections.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop",
      alt: "Aceternity UI dark animated components",
    },
    category: MOCK_RESOURCE_CATEGORIES[0],
    pricing: "Freemium",
    isFeatured: true,
    publishedAt: "2026-08-12T10:30:00.000Z",
  },
  {
    _id: "res-magic-ui",
    _type: "resource",
    title: "Magic UI",
    slug: { current: "magic-ui" },
    url: "https://magicui.design",
    description:
      "50+ animated components built with React, Typescript, Tailwind CSS, and Framer Motion designed for landing page conversion.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?q=80&w=1200&auto=format&fit=crop",
      alt: "Magic UI animated components library",
    },
    category: MOCK_RESOURCE_CATEGORIES[0],
    pricing: "Freemium",
    isFeatured: true,
    publishedAt: "2026-08-10T14:15:00.000Z",
  },
  {
    _id: "res-lucide-icons",
    _type: "resource",
    title: "Lucide Icons",
    slug: { current: "lucide-icons" },
    url: "https://lucide.dev",
    description:
      "Beautiful & consistent open-source icon toolkit made by the community. Over 1,400+ crisp vector icons ready for React and web apps.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop",
      alt: "Lucide icons vector library preview",
    },
    category: MOCK_RESOURCE_CATEGORIES[1],
    pricing: "Free",
    isFeatured: false,
    publishedAt: "2026-08-05T09:00:00.000Z",
  },
  {
    _id: "res-motion-framer",
    _type: "resource",
    title: "Motion (Framer Motion)",
    slug: { current: "framer-motion" },
    url: "https://motion.dev",
    description:
      "Production-ready animation and gesture library for React. Declarative syntax, spring physics, layout morphing, and GPU acceleration.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop",
      alt: "Motion library animation primitives preview",
    },
    category: MOCK_RESOURCE_CATEGORIES[3],
    pricing: "MIT",
    isFeatured: true,
    publishedAt: "2026-07-29T11:00:00.000Z",
  },
  {
    _id: "res-tailwind-v4",
    _type: "resource",
    title: "Tailwind CSS v4",
    slug: { current: "tailwind-css-v4" },
    url: "https://tailwindcss.com",
    description:
      "Next-generation utility-first CSS framework with an ultra-fast Rust engine, simplified CSS-first configuration, and native cascade layers.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=1200&auto=format&fit=crop",
      alt: "Tailwind CSS v4 engine and design tokens preview",
    },
    category: MOCK_RESOURCE_CATEGORIES[2],
    pricing: "MIT",
    isFeatured: false,
    publishedAt: "2026-07-25T16:20:00.000Z",
  },
  {
    _id: "res-threejs-journey",
    _type: "resource",
    title: "Three.js Journey",
    slug: { current: "threejs-journey" },
    url: "https://threejs-journey.com",
    description:
      "The definitive masterclass to learn WebGL, Three.js, GLSL shaders, Blender asset pipeline, and performance optimization from Bruno Simon.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?q=80&w=1200&auto=format&fit=crop",
      alt: "Three.js WebGL and GLSL shaders interactive course preview",
    },
    category: MOCK_RESOURCE_CATEGORIES[2],
    pricing: "Paid",
    isFeatured: true,
    publishedAt: "2026-07-20T12:00:00.000Z",
  },
  {
    _id: "res-radix-primitives",
    _type: "resource",
    title: "Radix Primitives",
    slug: { current: "radix-primitives" },
    url: "https://www.radix-ui.com/primitives",
    description:
      "Unstyled, accessible UI components for building high-quality design systems and web apps in React. Full keyboard navigation and WAI-ARIA.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop",
      alt: "Radix Primitives accessible UI tokens",
    },
    category: MOCK_RESOURCE_CATEGORIES[0],
    pricing: "MIT",
    isFeatured: false,
    publishedAt: "2026-07-16T15:30:00.000Z",
  },
  {
    _id: "res-v0-vercel",
    _type: "resource",
    title: "v0 by Vercel",
    slug: { current: "v0-by-vercel" },
    url: "https://v0.dev",
    description:
      "Generative AI system for prototyping and coding fullstack React UI components from natural language prompts, styled with Tailwind CSS.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop",
      alt: "v0 by Vercel AI generative UI prompt interface",
    },
    category: MOCK_RESOURCE_CATEGORIES[4],
    pricing: "Freemium",
    isFeatured: true,
    publishedAt: "2026-07-10T08:45:00.000Z",
  },
  {
    _id: "res-kokonut-ui",
    _type: "resource",
    title: "Kokonut UI",
    slug: { current: "kokonut-ui" },
    url: "https://kokonutui.com",
    description:
      "Collection of 100+ modern, copy-paste Tailwind and Framer Motion components with unique button physics, inputs, and card interactions.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1200&auto=format&fit=crop",
      alt: "Kokonut UI component library preview",
    },
    category: MOCK_RESOURCE_CATEGORIES[0],
    pricing: "Free",
    isFeatured: false,
    publishedAt: "2026-07-04T13:10:00.000Z",
  },
  {
    _id: "res-svgl",
    _type: "resource",
    title: "SVGL",
    slug: { current: "svgl" },
    url: "https://svgl.app",
    description:
      "A curated library of beautiful, high-quality SVG logos for modern web development frameworks, databases, cloud providers, and AI tooling.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=1200&auto=format&fit=crop",
      alt: "SVGL logo library preview",
    },
    category: MOCK_RESOURCE_CATEGORIES[1],
    pricing: "Free",
    isFeatured: false,
    publishedAt: "2026-06-28T09:20:00.000Z",
  },
  {
    _id: "res-fontshare",
    _type: "resource",
    title: "Fontshare",
    slug: { current: "fontshare" },
    url: "https://www.fontshare.com",
    description:
      "Free font service launched by the Indian Type Foundry offering high quality, professional fonts 100% free for personal and commercial use.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?q=80&w=1200&auto=format&fit=crop",
      alt: "Fontshare typography specimens preview",
    },
    category: MOCK_RESOURCE_CATEGORIES[5],
    pricing: "Free",
    isFeatured: false,
    publishedAt: "2026-06-22T14:40:00.000Z",
  },
  {
    _id: "res-hypercolor",
    _type: "resource",
    title: "Hypercolor",
    slug: { current: "hypercolor" },
    url: "https://hypercolor.dev",
    description:
      "Curated collection of modern Tailwind CSS color gradients with radial, conical, and mesh options ready for 1-click clipboard copy.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1200&auto=format&fit=crop",
      alt: "Hypercolor Tailwind CSS gradient generator preview",
    },
    category: MOCK_RESOURCE_CATEGORIES[6],
    pricing: "Free",
    isFeatured: false,
    publishedAt: "2026-06-17T11:15:00.000Z",
  },
  {
    _id: "res-gsap",
    _type: "resource",
    title: "GSAP (GreenSock)",
    slug: { current: "gsap" },
    url: "https://gsap.com",
    description:
      "Ultra high-performance JavaScript animation platform for complex SVG manipulation, canvas rendering, timeline syncing, and ScrollTrigger effects.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1200&auto=format&fit=crop",
      alt: "GSAP timeline animation platform preview",
    },
    category: MOCK_RESOURCE_CATEGORIES[3],
    pricing: "Freemium",
    isFeatured: false,
    publishedAt: "2026-06-11T10:05:00.000Z",
  },
  {
    _id: "res-codrops",
    _type: "resource",
    title: "Codrops UI Labs",
    slug: { current: "codrops-ui-labs" },
    url: "https://tympanus.net/codrops",
    description:
      "Creative frontend playground, WebGL shaders, smooth page transitions, interactive canvas demos, and experimental UI engineering.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=1200&auto=format&fit=crop",
      alt: "Codrops experimental web design and creative code",
    },
    category: MOCK_RESOURCE_CATEGORIES[7],
    pricing: "Free",
    isFeatured: true,
    publishedAt: "2026-06-05T08:30:00.000Z",
  },
  {
    _id: "res-raycast",
    _type: "resource",
    title: "Raycast",
    slug: { current: "raycast" },
    url: "https://www.raycast.com",
    description:
      "Blazing fast, extensible launcher built for developers to control tools, run scripts, manage clipboard history, and execute AI agent commands.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1200&auto=format&fit=crop",
      alt: "Raycast developer launcher and productivity toolkit preview",
    },
    category: MOCK_RESOURCE_CATEGORIES[4],
    pricing: "Freemium",
    isFeatured: false,
    publishedAt: "2026-05-30T15:00:00.000Z",
  },
  {
    _id: "res-uiverse",
    _type: "resource",
    title: "Uiverse.io",
    slug: { current: "uiverse-io" },
    url: "https://uiverse.io",
    description:
      "The largest open-source library of community-crafted CSS and Tailwind UI elements: futuristic buttons, fluid loaders, cards, and toggles.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop",
      alt: "Uiverse open source CSS and UI elements preview",
    },
    category: MOCK_RESOURCE_CATEGORIES[2],
    pricing: "MIT",
    isFeatured: false,
    publishedAt: "2026-05-24T09:40:00.000Z",
  },
  {
    _id: "res-realtime-colors",
    _type: "resource",
    title: "Realtime Colors",
    slug: { current: "realtime-colors" },
    url: "https://www.realtimecolors.com",
    description:
      "Visualize color palettes, contrast ratios, and typographic hierarchies in real-time across a live mock landing page layout.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop",
      alt: "Realtime Colors palette design system simulator preview",
    },
    category: MOCK_RESOURCE_CATEGORIES[6],
    pricing: "Free",
    isFeatured: false,
    publishedAt: "2026-05-18T13:20:00.000Z",
  },
  {
    _id: "res-realtime-colors-v2",
    _type: "resource",
    title: "Realtime Colors",
    slug: { current: "realtime-colors" },
    url: "https://www.realtimecolors.com",
    description:
      "Visualize color palettes, contrast ratios, and typographic hierarchies in real-time across a live mock landing page layout.",
    coverImage: {
      url: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop",
      alt: "Realtime Colors palette design system simulator preview",
    },
    category: MOCK_RESOURCE_CATEGORIES[6],
    pricing: "Free",
    isFeatured: false,
    publishedAt: "2026-05-18T13:20:00.000Z",
  },
]
